services:
  app:
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      DP_APP_ID: 'drupalforge'
      APP_ROOT: '/usr/share/nginx/html'
      WEB_ROOT: '/usr/share/nginx/html'
      CODES_USER_DATA_DIR: '/usr/share/nginx/html/.vscode'
      CODES_WORKING_DIR: '/usr/share/nginx/html'
      CODES_ENABLE: 'no'
    volumes:
      - "..:/usr/share/nginx/html"